# Generated by Django 4.2.14 on 2024-07-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_customtoken_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='seatNumber',
            field=models.IntegerField(default=0),
        ),
    ]
