# Generated by Django 5.0.7 on 2024-08-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_customuser_seatnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='seatNumber',
        ),
    ]
