# Generated by Django 5.0.7 on 2024-08-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_customuser_groups_customuser_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
    ]
