# Generated by Django 5.0.7 on 2024-08-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_event_attendees_remove_event_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
